// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiGwsaMSye8NGD4mqF6RUKLYyPUbEjGQc',
    appId: '1:366529520305:web:2a000eb559ded1b825f890',
    messagingSenderId: '366529520305',
    projectId: 'nyobain-firebase-8996e',
    authDomain: 'nyobain-firebase-8996e.firebaseapp.com',
    storageBucket: 'nyobain-firebase-8996e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5aDtdRnhiRDe3HiuRLun3mW8VZtVfPjw',
    appId: '1:366529520305:android:a7757abdfe76615325f890',
    messagingSenderId: '366529520305',
    projectId: 'nyobain-firebase-8996e',
    storageBucket: 'nyobain-firebase-8996e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBiGwsaMSye8NGD4mqF6RUKLYyPUbEjGQc',
    appId: '1:366529520305:web:c98e08955dc333c525f890',
    messagingSenderId: '366529520305',
    projectId: 'nyobain-firebase-8996e',
    authDomain: 'nyobain-firebase-8996e.firebaseapp.com',
    storageBucket: 'nyobain-firebase-8996e.firebasestorage.app',
  );
}
